double square (double x );                    
double cube(double x );
double Inverse (double x );                       
double E(double om_m,double om_L,double om_r, double x) ;
double Growth(double z, double om_m, double  om_L, double om_r);
double  Chi(double om_m, double om_L,double om_r, double h, double x);
double Tk_BBKS_CDM(double k,double om_r,  double om_CDM, double  om_b , double  om_L,double h);
double Tk_BBKS_Baryon(double k,double om_r,  double om_CDM, double  om_b , double  om_L , double h);
double Tk_EH_full(double k,double om_r , double om_CDM, double  om_b , double  om_L, double h,  double CMB_temp);
double Pk_BBKS_Baryon(double k,double om_r,  double om_CDM, double  om_b , double  om_L ,double A, double h, double ns ,double z);
double Pk_EH(double k,double om_r,  double om_CDM, double  om_b , double  om_L ,double A, double CMB_temp, double h, double ns ,double z);
double Pk_BBKS_CDM(double k,double om_r,  double om_CDM, double  om_b , double  om_L ,double A, double h, double ns ,double z);
double P_NL_halomodel_Takahashi(double k, double Pk_linear,double Omega_m,double Omega_w, double ksigma,double CC,double neff, double w_DE, double h ) ;
double P_NL_halomodel(double k, double Pk_linear,double Omega_m, double ksigma,double CC,  double neff, double h );
double Sigmaa_BBKS(double R1,double Omega_r, double Omega_cdm, double  Omega_b , double  Omega_L ,double A, double h, double ns, double z);
double Sigmaa_EH(double R1,double Omega_r, double Omega_cdm, double  Omega_b , double  Omega_L ,double A, double h, double ns, double z);
double Sigmaa_Taka(double R1,double Omega_r, double Omega_cdm, double  Omega_b , double  Omega_L ,double A, double h, double ns, double z);
double W_PhiPhi(double om_m, double om_L,double om_r, double h, double z);
double W_kCMB(double om_m, double om_L,double om_r, double h, double z);
double W_kGal(double om_m, double om_L,double om_r, double h, double z);